---
environment_suffix: "_preprod"
project_slug: "{{ base_project_slug }}{{ environment_suffix }}"

project_dir: /{{project_base_dir}}{{ environment_suffix }}
backend_static_path: "{{ project_dir }}/backend_static"
media_static_path: "{{ project_dir }}/backend/media"

frontend_branch: monorepo
backend_branch: monorepo
n_workers: 1

node_version: 18.18.0

backend_application_port: 8045  # must be unique for each project on the same server
frontend_application_port: 3045  # must be unique for each project on the same server

public_hostnames:
  - preprod.demometre.tlscp.fr
  - preprod.demometre.org

project_db_name: "{{ project_slug }}"

environment_name: preprod
