# Generated by Django 5.0.8 on 2025-01-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("open_democracy_back", "0068_alter_question_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="criteria",
            name="concatenated_code",
            field=models.CharField(default="", max_length=15),
        ),
    ]
