# Generated by Django 5.0.8 on 2025-10-06 10:07

import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("open_democracy_back", "0069_alter_criteria_concatenated_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="international_block_countries",
            field=wagtail.fields.StreamField(
                [
                    (
                        "country",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "button_name_fr",
                                    wagtail.blocks.CharBlock(
                                        label="Nom du bouton (fr)"
                                    ),
                                ),
                                (
                                    "button_name_en",
                                    wagtail.blocks.CharBlock(
                                        label="Nom du bouton (en)"
                                    ),
                                ),
                                ("link", wagtail.blocks.URLBlock(label="Lien")),
                            ],
                            label="Pays",
                            label_format="Pays : {button_name}",
                        ),
                    )
                ],
                blank=True,
                verbose_name="Liste des pays",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="international_block_intro",
            field=models.TextField(blank=True, verbose_name="Intro du bloc Blog"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="international_block_title",
            field=models.CharField(
                blank=True,
                help_text="Si ce champ est vide, cette section ne s'affichera pas sur l'accueil",
                max_length=68,
                verbose_name="Titre du bloc International",
            ),
        ),
    ]
