# Generated by Django 5.0.11 on 2025-01-30 17:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0069_alter_criteria_concatenated_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentrepresentativity',
            name='acceptability_threshold',
        ),
    ]
