# Generated by Django 5.0.8 on 2025-01-29 14:45

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("open_democracy_back", "0069_alter_criteria_concatenated_code"),
        ("wagtailcore", "0093_uploadedfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipativeProcessPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "processes_title",
                    models.CharField(max_length=128, verbose_name="Titre"),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        default="", verbose_name="Description"
                    ),
                ),
                (
                    "add_participative_process_call_to_action",
                    models.CharField(
                        default="Valider",
                        max_length=32,
                        verbose_name="Bouton ajouter un processus participatif",
                    ),
                ),
                (
                    "confirm_call_to_action",
                    models.CharField(
                        default="Valider",
                        max_length=32,
                        verbose_name="Bouton de confirmation",
                    ),
                ),
                (
                    "skip_call_to_action",
                    models.CharField(
                        default="Valider",
                        max_length=32,
                        verbose_name="Bouton pour passer l'étape",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ParticipativeProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "assessment",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participative_processes",
                        to="open_democracy_back.assessment",
                    ),
                ),
                (
                    "response_choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="open_democracy_back.responsechoice",
                        verbose_name="Catégorie",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="participation",
            name="participative_processes",
            field=models.ManyToManyField(
                related_name="participations",
                to="open_democracy_back.participativeprocess",
            ),
        ),
    ]
