# Generated by Django 5.0.11 on 2025-01-31 09:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_democracy_back', '0070_remove_assessmentrepresentativity_acceptability_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentRepresentativityCriteriaRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptability_threshold', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Seuil d'acceptabilité")),
                ('assessment_representativity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_choice_rules', to='open_democracy_back.assessmentrepresentativity')),
                ('response_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_representativity_criteria_rules', to='open_democracy_back.responsechoice', verbose_name='Réponse')),
            ],
            options={
                'unique_together': {('assessment_representativity', 'response_choice')},
            },
        ),
    ]
