# Generated by Django 5.0.8 on 2025-01-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "open_democracy_back",
            "0070_participativeprocesspage_participativeprocess_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_participative_process_question",
            field=models.BooleanField(
                default=False,
                verbose_name="Cette question concerne les process participatifs",
            ),
        ),
    ]
