# Generated by Django 5.0.8 on 2025-02-05 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("open_democracy_back", "0071_question_is_participative_process_question"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="participationresponse",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="participationresponse",
            name="participative_process",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participation_responses",
                to="open_democracy_back.participativeprocess",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="participationresponse",
            unique_together={("participation", "question", "participative_process")},
        ),
    ]
