# Generated by Django 5.0.8 on 2025-02-24 11:16

from django.db import migrations, models


def update_assessment_locality_type(apps, schema_editor):
    Assessment = apps.get_model("open_democracy_back", "Assessment")
    for assessment in Assessment.objects.all():
        if assessment.locality_type == "municipality":
            assessment.locality_type = "city"
            assessment.save()
        elif assessment.locality_type == "intercommunality":
            assessment.locality_type = "epci"
            assessment.save()



class Migration(migrations.Migration):
    dependencies = [
        (
            "open_democracy_back",
            "0072_alter_participationresponse_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="locality_type",
            field=models.CharField(
                choices=[
                    ("city", "Commune"),
                    ("epci", "EPCI"),
                    ("department", "Département"),
                    ("region", "Région"),
                ],
                default="city",
                max_length=32,
                verbose_name="Type de localité",
            ),
        ),
        migrations.AlterField(
            model_name="representativitycriteria",
            name="survey_locality",
            field=models.CharField(
                choices=[
                    ("city", "Commune"),
                    ("epci", "EPCI"),
                    ("department", "Département"),
                    ("region", "Région"),
                ],
                default="city",
                max_length=32,
                verbose_name="Échelon questionnaire",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="survey_locality",
            field=models.CharField(
                choices=[
                    ("city", "Commune"),
                    ("epci", "EPCI"),
                    ("department", "Département"),
                    ("region", "Région"),
                ],
                default="city",
                max_length=32,
                unique=True,
                verbose_name="Échelon du questionnaire",
            ),
        ),
        migrations.RunPython(update_assessment_locality_type, migrations.RunPython.noop)
    ]
