# Generated by Django 5.0.8 on 2025-02-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("open_democracy_back", "0073_alter_assessment_locality_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="code",
            field=models.CharField(
                default="",
                help_text="Nom court du questionnaire pour les menus de l'interface admin",
                max_length=2,
                verbose_name="code",
            ),
        ),
    ]
