# Generated by Django 5.0.8 on 2025-06-16 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("open_democracy_back", "0071_assessmentrepresentativitycriteriarule"),
        ("open_democracy_back", "0074_alter_survey_code"),
    ]

    operations = []
