# Generated by Django 5.0.8 on 2025-06-20 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("open_democracy_back", "0075_merge_20250616_0756"),
    ]

    operations = [
        migrations.AlterField(
            model_name="representativitycriteria",
            name="profiling_question",
            field=models.OneToOneField(
                limit_choices_to={"type__in": ["unique_choice", "multiple_choice"]},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="representativity_criteria",
                to="open_democracy_back.profilingquestion",
                verbose_name="Question de profilage reliée",
            ),
        ),
    ]
