# Generated by Django 5.0.8 on 2025-08-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "open_democracy_back",
            "0076_alter_representativitycriteria_profiling_question",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="code",
            field=models.CharField(max_length=12, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="region",
            name="code",
            field=models.CharField(max_length=12, verbose_name="Code"),
        ),
    ]
