# Generated by Django 5.0.8 on 2025-10-14 07:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("open_democracy_back", "0070_homepage_international_block_countries_and_more"),
        (
            "open_democracy_back",
            "0076_alter_representativitycriteria_profiling_question",
        ),
    ]

    operations = []
