# Generated by Django 5.0.8 on 2025-10-02 16:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("open_democracy_back", "0077_alter_department_code_alter_region_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="criteria",
            options={
                "ordering": ["concatenated_code"],
                "verbose_name": "3. Critère",
                "verbose_name_plural": "3. Critères",
            },
        ),
    ]
