# Generated by Django 5.0.8 on 2025-10-22 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("open_democracy_back", "0077_merge_20251014_0720"),
        ("open_democracy_back", "0078_alter_criteria_options"),
    ]

    operations = []
