# Generated by Django 5.0.14 on 2025-12-12 11:41

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "open_democracy_back",
            "0080_alter_blogpost_locale_alter_resource_locale_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectpage",
            name="objective_block_data",
            field=wagtail.fields.StreamField(
                [("objective", 1)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Titre"}),
                    1: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0)]],
                        {"label": "Objectif", "label_format": "Objectif : {title}"},
                    ),
                },
                verbose_name="Les objectifs",
            ),
        ),
    ]
