# Generated by Django 5.0.14 on 2025-12-12 11:43

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("open_democracy_back", "0081_alter_projectpage_objective_block_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectpage",
            name="objective_block_data",
            field=wagtail.fields.StreamField(
                [("objective", 2)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtailsvg.blocks.SvgChooserBlock",
                        (),
                        {
                            "help_text": "Pour ajouter un SVG d'abord l'ajouter dans le menu SVG",
                            "label": "Icone au format svg",
                        },
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Titre"}),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("svg", 0), ("title", 1)]],
                        {"label": "Objectif", "label_format": "Objectif : {title}"},
                    ),
                },
                verbose_name="Les objectifs",
            ),
        ),
    ]
