---
environment_suffix: "_belgique_preprod"
project_slug: "{{ base_project_slug }}{{ environment_suffix }}"

project_dir: /{{project_base_dir}}{{ environment_suffix }}
backend_static_path: "{{ project_dir }}/backend_static"
media_static_path: "{{ project_dir }}/backend/media"

frontend_branch: dev
backend_branch: be
n_workers: 1

node_version: 18.18.0

backend_application_port: 8047  # must be unique for each project on the same server
frontend_application_port: 3047  # must be unique for each project on the same server

public_hostnames:
  - preprod.belgique.demometre.tlscp.fr

project_db_name: "{{ project_slug }}"

environment_name: belgique_preprod
