
describe('go through questionnaire', () => {
  it('logs in', () => {
    cy.request('http://localhost:8000/api/e2e/clean-data').as('clean-data')

    cy.get('@clean-data')
    cy.login("user@telescoop.fr", "password")
    cy.wait(400)
    cy.visit("/evaluation/localisation")
    cy.wait(400)
    cy.getBySel('zip-code').type('99901')
    cy.getBySel('search').click()
    cy.wait(400)
    cy.getBySel('locality-municipality-99901').click()
    cy.getBySel('submit').click()
    cy.getBySel('quick-choose').click()
    cy.getBySel('initiator-cgu-consent').click()
    cy.getBySel('consent-submit').click()
    cy.getBySel('initiator-name').type('Mairie de la ville test')
    cy.getBySel('initiator-type-collectivity').click()
    cy.getBySel('initiator-submit').click()
    cy.getBySel('start-objective-questions').click()
    cy.getBySel('confirm-objective-questions').click()
    cy.getBySel('start-participation').click()
    cy.getBySel('participation-board-continue').click()
    // choose role
    cy.selectChoice(0)
    cy.submitQuestion()
    cy.getBySel('affinage-continue').click()
    cy.getBySel('rosette-start').click()
    // first question
    cy.getBySel('question-statement').contains('Question 1')
    cy.selectChoice(0)
    cy.submitQuestion()
    cy.getBySel('question-statement').contains('Question 2')
    cy.selectChoice(1)
    cy.selectChoice(2)
    cy.submitQuestion()
    cy.getBySel('question-statement').contains('Question 3')
    cy.selectCategory('Catégorie 1', 3)
    cy.selectCategory('Catégorie 2', 4)
    cy.submitQuestion()
    cy.getBySel('question-statement').contains('Question 4')
    cy.selectChoice(0)
    cy.submitQuestion()
    cy.getBySel('question-statement').contains('Question 5')
    cy.inputPercentage(50)
    cy.submitQuestion()
    cy.getBySel('question-statement').contains('Question 5')
    cy.inputNumber(3)
    cy.submitQuestion()
    // questionnaire is done, URL should be
    cy.url().should('match', /\/evaluation\/[a-z0-9-]+\/questionnaire/)


  })
})
