---
environment_suffix: "_prod"
project_slug: "{{ base_project_slug }}{{ environment_suffix }}"

project_dir: /{{project_base_dir}}{{ environment_suffix }}
backend_static_path: "{{ project_dir }}/backend_static"
media_static_path: "{{ project_dir }}/backend/media"

frontend_branch: main
backend_branch: main
n_workers: 4

node_version: 18.18.0

backend_application_port: 8046  # must be unique for each project on the same server
frontend_application_port: 3046  # must be unique for each project on the same server

public_hostnames:
  - demometre.org
  - demometre.tlscp.fr
  - democratieouverte.tlscp.fr

project_db_name: do

environment_name: preprod
