# Generated by Django 3.2.12 on 2022-06-30 15:09

from django.conf import settings
from django.core.management import BaseCommand

from open_democracy_back.data.regions import REGIONS
from open_democracy_back.data.departements import DEPARTEMENTS
from open_democracy_back.data.epci import EPCI as EPCIS
from open_democracy_back.data.communes import COMMUNES
from open_democracy_back.models import (
    Municipality,
    Region,
    Department,
    EPCI,
    ZipCode,
    MunicipalityOrderByEPCI,
)


country = settings.COUNTRY


def import_political_division(apps, _):
    bulk_region = []
    for region in REGIONS:
        bulk_region.append(Region(name=region["nom"], code=region["code"]))
    bulk_region.append(Region(name="Région d'outre-mer", code="97"))
    Region.objects.bulk_create(bulk_region)
    regions = {region.code: region for region in Region.objects.all()}

    bulk_department = []
    for department in DEPARTEMENTS:
        bulk_department.append(
            Department(
                name=department["nom"],
                code=department["code"],
                region=regions[department["region"]],
            )
        )
    bulk_department.append(
        Department(name="Département d'outre-mer", code="97", region=regions["97"])
    )

    Department.objects.bulk_create(bulk_department)
    departments = {
        department.code: department for department in Department.objects.all()
    }

    for commune_dict in COMMUNES:
        if country == "fr":
            department_code = commune_dict.get("departement", "97")
        else:
            department_code = commune_dict["departement"]
        commune = Municipality(
            code=commune_dict["code"],
            name=commune_dict["nom"],
            department=departments[department_code],
            population=commune_dict.get("population", 0),
        )
        commune.save()
        for zip_code_value in commune_dict.get("codesPostaux", []):
            ZipCode(code=zip_code_value, municipality=commune).save()

    for epci_dict in EPCIS:
        member_codes = [member["code"] for member in epci_dict["membres"]]
        municipalities = Municipality.objects.filter(code__in=member_codes)
        epci = EPCI(
            name=epci_dict["nom"],
            population=epci_dict.get("populationTotale")
            or epci_dict.get("populationMunicipale", 0),
        )
        epci.save()
        bulk_municipality_order_by_EPCI = []
        for municipality in municipalities:
            bulk_municipality_order_by_EPCI.append(
                MunicipalityOrderByEPCI(epci=epci, municipality=municipality)
            )
        MunicipalityOrderByEPCI.objects.bulk_create(bulk_municipality_order_by_EPCI)


def removeMunicipalitiesAndEPCI(apps, _):
    if settings.IS_TEST:
        return
    apps.get_model("open_democracy_back", "Municipality").objects.all().delete()
    apps.get_model("open_democracy_back", "Region").objects.all().delete()
    apps.get_model("open_democracy_back", "Department").objects.all().delete()
    apps.get_model("open_democracy_back", "EPCI").objects.all().delete()
    apps.get_model("open_democracy_back", "ZipCode").objects.all().delete()
    apps.get_model(
        "open_democracy_back", "MunicipalityOrderByEPCI"
    ).objects.all().delete()


class Command(BaseCommand):
    help = "Command to import political division"

    def handle(self, *args, **options):
        import_political_division()
