---
environment_suffix: "_belgique_prod"
project_slug: "{{ base_project_slug }}{{ environment_suffix }}"

project_dir: /{{project_base_dir}}{{ environment_suffix }}
backend_static_path: "{{ project_dir }}/backend_static"
media_static_path: "{{ project_dir }}/backend/back/media"

frontend_branch: main
backend_branch: main
n_workers: 4

node_version: 18.18.0

backend_application_port: 8048  # must be unique for each project on the same server
frontend_application_port: 3048  # must be unique for each project on the same server

main_hostname: belgique.demometre.org

public_hostnames:
  - "{{ main_hostname }}"

redirect_hostnames:
  - belgique.demometre.tlscp.fr

all_hostnames: "{{ public_hostnames + redirect_hostnames }}"
https_hostnames: "{{ all_hostnames }}"

project_db_name: "{{ project_slug }}"

environment_name: belgique_prod

country: BE
